export const BASE_URL = 'https://api.themoviedb.org/3'
export const API_KEY = 'a4e937f25970846aa57ad5fc10096416'
export const IMAGE_URL = 'https://image.tmdb.org/t/p/original'
export const ORIGINALS_URL = '/discover/movie?with_network=213'
export const ACTION_URL= '/discover/movie?with_genres=9648'
export const COMEDY_URL= '/discover/movie?with_genres=35'
export const HORROR_URL= '/discover/movie?with_genres=27'
export const ROMANTIC_URL= '/discover/movie?with_genres=10749'
export const DOCUMENTARIES = '/discover/movie?with_genres=99'

